id: A81A20750
title: Aspiration to Accomplish Every Aim
type: translation
pechas:
- I2790EB3B
- I04CB0888
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:47.458154
  last_modified_at: 2023-01-04 12:06:47.458158
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I2790EB3B/102D: CDA4
  I04CB0888/2BCB: CDA4
